exports.goodbye = require('./goodbye.js')
exports.gracias = require('./gracias.js')
exports.greet = require('./greetings.js')
exports.help = require('./help.js')
exports.rude = require('./rude.js')
exports.none = require('./none.js')
exports.personal = require('./personal.js')
exports.teaching = require('./teaching.js')
